export default {
  nav: {
    id: "nav",
    Title: "Yfluo's IP",
    IPinfo: "IP 信息",
    Connectivity: "网络连通性",
    WebRTC: "WebRTC 测试",
    DNSLeakTest: "DNS 泄漏测试",
  },
  ipInfos: {
    id: "ipinfos",
    Title: "IP 信息",
    Simple: "简约",
    Map: "地图",
    MapUnavailable: "地图不可用",
    Source: "来源",
    IP: "IP 地址",
    Country: "国家",
    Region: "地区",
    City: "城市",
    ISP: "ISP",
    ASN: "ASN",
    IPv4Error: "获取失败或不存在 IPv4 地址",
    IPv6Error: "获取失败或不存在 IPv6 地址",
  },
  connectivity: {
    id: "connectivity",
    Title: "网络连通性",
    StatusWait: "待检测",
    StatusAvailable: "可用",
    StatusUnavailable: "不可用",
    StatusTimeout: "超时或不可用",
    checking: "检查中...",
  },
  webrtc: {
    id: "webrtc",
    Title: "WebRTC 测试",
    StatusWait: "待检测或连接错误",
    StatusError: "测试出错",
  },
  dnsleaktest: {
    id: "dnsleaktest",
    Name: "测试",
    Title: "DNS 泄漏测试",
    Endpoint: "DNS 出口",
    EndpointCountry: "出口地区",
    StatusWait: "待检测",
    StatusError: "测试出错",
  },
  ipcheck: {
    id: "ipcheck",
    Title: "IP 查询",
    Placeholder: "请输入 IP 地址",
    Button: "查询",
    Error: "请输入有效的 IPv4 或 IPv6 地址。",
  },
  alert: {
    id: "alert",
    OhNo: "糟糕！",
    Congrats: "恭喜！",
    OhNo_Message: "你未连接代理。",
    Congrats_Message: "你当前成功连接代理。",
  },
  page: {
    title:
      "Yfluo 的 IP",
  },
};
