export default {
  nav: {
    id: "nav",
    Title: "Yfluo's IP",
    IPinfo: "IP Infos",
    Connectivity: "Connectivity",
    WebRTC: "WebRTC Test",
    DNSLeakTest: "DNS Leak Test",
  },
  ipInfos: {
    id: "ipinfos",
    Title: "IP Infos",
    Simple: "Simple",
    Map: "Map",
    MapUnavailable: "Map Unavailable",
    Source: "Source",
    IP: "IP Address",
    Country: "Country",
    Region: "Region",
    City: "City",
    ISP: "ISP",
    ASN: "ASN",
    IPv4Error: "Fetch Failed or No IPv4 Address",
    IPv6Error: "Fetch Failed or No IPv6 Address",
  },
  connectivity: {
    id: "connectivity",
    Title: "Network Connectivity",
    StatusWait: "Awaiting Test",
    StatusAvailable: "OK",
    StatusUnavailable: "Unavailable",
    StatusTimeout: "Timeout or Unavailable",
    checking: "Checking...",
  },
  webrtc: {
    id: "webrtc",
    Title: "WebRTC Test",
    StatusWait: "Awaiting Test or Connection Error",
    StatusError: "Test Error",
  },
  dnsleaktest: {
    id: "dnsleaktest",
    Name: "Test",
    Title: "DNS Leak Test",
    Endpoint: "DNS Endpoint",
    EndpointCountry: "Endpoint Region",
    StatusWait: "Awaiting Test",
    StatusError: "Test Error",
  },
  ipcheck: {
    id: "ipcheck",
    Title: "IP Check",
    Placeholder: "Please enter an IP address",
    Button: "Check",
    Error: "Please enter a valid IPv4 or IPv6 address.",
  },
  alert: {
    id: "alert",
    OhNo: "Oh No!",
    Congrats: "Congrats!",
    OhNo_Message:
      "You are not connected to a proxy.",
    Congrats_Message:
      "You are now connected to a proxy.",
  },
  page: {
    title:
      "Yfluo's IP",
  },
};
